services:
  web:
    build: .
    image: kitsune_finance:latest
    ports:
      - "13522:80"
    environment:
      - RAILS_ENV=development
    volumes:
      - ~/.local/share/KitsuneFinance:/rails/storage
