services:
  web:
    build: .
    image: kitsune_finance:latest
    ports:
      - "13522:80"
    environment:
      - RAILS_ENV=development
    volumes:
      - ./storage:/rails/storage
      - ./app:/rails/app
      - ./config:/rails/config
      - ./db:/rails/db
      - ./lib:/rails/lib
      - ./bin:/rails/bin
    command: ["sh", "-c", "bin/rails tailwindcss:build && exec ./bin/thrust ./bin/rails server"]
