services:
  web:
    build: .
    image: kitsune_finance:latest
    ports:
      - "13522:80"
    environment:
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - RAILS_RELATIVE_URL_ROOT=${RAILS_RELATIVE_URL_ROOT:-}
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
      - APP_HOST=${APP_HOST:-localhost}
    volumes:
      - ./storage:/rails/storage
    restart: unless-stopped
