services:
  web:
    build: .
    image: kitsune_finance:latest
    ports:
      - "13522:80"
    environment:
      - RAILS_ENV=development
      - DATABASE_PATH=/rails/data/development.sqlite3
    volumes:
      - ~/kitsune_finance_data:/rails/data
